#!/bin/bash

set -e

#
# Fetch base image
docker pull cherrypick/fedora-base

#
# Bootstrap fedora-base
docker build -t fedora-base images/fedora-base/
docker run --rm --entrypoint cat fedora-base /usr/src/build/sysroot.tar | \
        docker import - cherrypick/fedora-base

#
# Prune build artifacts
docker image rm fedora-base
docker image prune -f
