#!/bin/bash

set -e

#
# Fetch base image
docker pull cherrypick/archlinux-base

#
# Bootstrap archlinux-base
docker build -t archlinux-base images/archlinux-base/
docker run --rm --entrypoint cat archlinux-base /usr/src/build/sysroot.tar | \
        docker import - cherrypick/archlinux-base

#
# Prune build artifacts
docker image rm archlinux-base
docker image prune -f
