#!/bin/bash

set -e

#
# Run entropy daemon
CID_HAVEGED=`docker run --rm --privileged -d harbur/haveged`

#
# Bootstrap archlinux-base
docker build -t archlinux-base images/archlinux-base/
CID=`docker run --privileged --rm -dit archlinux-base /bin/bash`
docker exec -t --privileged "$CID" make -C /usr/src/build/ build
docker exec -t --privileged "$CID" make -C /usr/src/build/ rootfs.tar
docker cp "$CID":/usr/src/build/rootfs.tar .
docker stop "$CID"
docker import rootfs.tar cherrypick/archlinux-base

#
# Stop entropy daemon
docker stop "$CID_HAVEGED"
