#!/bin/bash

set -e

#
# Bootstrap fedora-base
docker build -t fedora-base images/fedora-base/
docker run --rm --entrypoint cat fedora-base /usr/src/build/sysroot.tar | \
        docker import - cherrypick/fedora-base
