#!/bin/bash

set -e

#
# Bootstrap archlinux-base
docker build -t archlinux-base images/archlinux-base/
docker run --rm --entrypoint cat archlinux-base /usr/src/build/sysroot.tar | \
        docker import - cherrypick/archlinux-base
