#!/bin/bash

set -e

#
# Print early log-separator
echo "Running CI setup..."

#
# Pull all our dependencies
docker pull harbur/haveged
docker pull cherrypick/archlinux-base
docker pull cherrypick/fedora-base

#
# Print final log-separator
echo "CI setup finished"
