#!/bin/bash

set -e

#
# Print early log-separator
echo "Running CI setup..."

#
# Pull all our dependencies
install-package qemu-user-static
docker pull harbur/haveged
docker pull cherrypick/archlinux-base
docker pull cherrypick/fedora-base

#
# Run haveged detached to get entropy
docker run --rm --privileged -d harbur/haveged

#
# Print final log-separator
echo "CI setup finished"
