#!/bin/bash

set -e

#
# Print early log-separator
echo "Running CI setup..."

#
# Pull all our dependencies
sudo apt-get update
sudo apt-get install -y qemu-user-static
docker pull harbur/haveged

#
# Run haveged detached to get entropy
docker run --rm --privileged -d harbur/haveged

#
# Print final log-separator
echo "CI setup finished"
