#!/bin/bash

set -e

#
# Test archlinux-base
#
# The new image was imported by the previous build into our docker
# layer cache. Hence, simply re-run the entire build to verify that
# the new image can bootstrap itself.
docker build images/archlinux-base/
